version: '3.8'

services:
  transfer-website:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transfer-website
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    networks:
      - transfer-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - nginx_logs:/var/log/nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transfer-website.rule=Host(`seu-dominio.com`)"
      - "traefik.http.routers.transfer-website.entrypoints=websecure"
      - "traefik.http.routers.transfer-website.tls.certresolver=letsencrypt"
      - "traefik.http.services.transfer-website.loadbalancer.server.port=80"

networks:
  transfer-network:
    driver: bridge

volumes:
  nginx_logs:
    driver: local 