// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://chvfqtutihudfnxpvfzt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNodmZxdHV0aWh1ZGZueHB2Znp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMyMDEyNzgsImV4cCI6MjA0ODc3NzI3OH0.4aUrl3Jl0DEhM02iGsffmW6U3AML41JwMKcUepk_U5c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);